// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function ConnectWithInvite(arg1) {
  return window['go']['app']['App']['ConnectWithInvite'](arg1);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function GenerateInvite(arg1) {
  return window['go']['app']['App']['GenerateInvite'](arg1);
}

export function GetAboutInfo() {
  return window['go']['app']['App']['GetAboutInfo']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConnectionDetails() {
  return window['go']['app']['App']['GetConnectionDetails']();
}

export function GetErrorMessage() {
  return window['go']['app']['App']['GetErrorMessage']();
}

export function GetLogContent() {
  return window['go']['app']['App']['GetLogContent']();
}

export function GetMode() {
  return window['go']['app']['App']['GetMode']();
}

export function GetNodes() {
  return window['go']['app']['App']['GetNodes']();
}

export function GetNodesWithLatency() {
  return window['go']['app']['App']['GetNodesWithLatency']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function GetWGServers() {
  return window['go']['app']['App']['GetWGServers']();
}

export function IsNetworkAdapterReady() {
  return window['go']['app']['App']['IsNetworkAdapterReady']();
}

export function OpenLogs() {
  return window['go']['app']['App']['OpenLogs']();
}

export function SaveWGSettings(arg1, arg2) {
  return window['go']['app']['App']['SaveWGSettings'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['app']['App']['SetMode'](arg1);
}

export function WGCreateRoom(arg1, arg2) {
  return window['go']['app']['App']['WGCreateRoom'](arg1, arg2);
}

export function WGDisconnect() {
  return window['go']['app']['App']['WGDisconnect']();
}

export function WGGetInviteCode() {
  return window['go']['app']['App']['WGGetInviteCode']();
}

export function WGGetStatus() {
  return window['go']['app']['App']['WGGetStatus']();
}

export function WGJoinRoom(arg1, arg2, arg3) {
  return window['go']['app']['App']['WGJoinRoom'](arg1, arg2, arg3);
}
