// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ConnectWithInvite(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GenerateInvite(arg1:string):Promise<string>;

export function GetAboutInfo():Promise<app.AboutInfo>;

export function GetConfig():Promise<app.ConfigInfo>;

export function GetErrorMessage():Promise<string>;

export function GetLogContent():Promise<string>;

export function GetNodes():Promise<Array<app.NodeInfo>>;

export function GetState():Promise<string>;

export function IsNetworkAdapterReady():Promise<boolean>;

export function OpenLogs():Promise<void>;
