// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function ConnectWithInvite(arg1) {
  return window['go']['app']['App']['ConnectWithInvite'](arg1);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function ExpressCreateRoom(arg1) {
  return window['go']['app']['App']['ExpressCreateRoom'](arg1);
}

export function ExpressDisconnect() {
  return window['go']['app']['App']['ExpressDisconnect']();
}

export function ExpressGetState() {
  return window['go']['app']['App']['ExpressGetState']();
}

export function ExpressJoinRoom(arg1, arg2) {
  return window['go']['app']['App']['ExpressJoinRoom'](arg1, arg2);
}

export function ExpressLeaveRoom() {
  return window['go']['app']['App']['ExpressLeaveRoom']();
}

export function ExpressReconnect() {
  return window['go']['app']['App']['ExpressReconnect']();
}

export function ExpressRepairService() {
  return window['go']['app']['App']['ExpressRepairService']();
}

export function ExpressRevealRoomCode() {
  return window['go']['app']['App']['ExpressRevealRoomCode']();
}

export function GenerateInvite(arg1) {
  return window['go']['app']['App']['GenerateInvite'](arg1);
}

export function GetAboutInfo() {
  return window['go']['app']['App']['GetAboutInfo']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConnectionDetails() {
  return window['go']['app']['App']['GetConnectionDetails']();
}

export function GetErrorMessage() {
  return window['go']['app']['App']['GetErrorMessage']();
}

export function GetLogContent() {
  return window['go']['app']['App']['GetLogContent']();
}

export function GetMode() {
  return window['go']['app']['App']['GetMode']();
}

export function GetNodes() {
  return window['go']['app']['App']['GetNodes']();
}

export function GetNodesWithLatency() {
  return window['go']['app']['App']['GetNodesWithLatency']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function IsNetworkAdapterReady() {
  return window['go']['app']['App']['IsNetworkAdapterReady']();
}

export function OpenLogs() {
  return window['go']['app']['App']['OpenLogs']();
}

export function SaveExpressSettings(arg1, arg2) {
  return window['go']['app']['App']['SaveExpressSettings'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['app']['App']['SetMode'](arg1);
}
