// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function ConnectWithInvite(arg1) {
  return window['go']['app']['App']['ConnectWithInvite'](arg1);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function GenerateInvite(arg1) {
  return window['go']['app']['App']['GenerateInvite'](arg1);
}

export function GetAboutInfo() {
  return window['go']['app']['App']['GetAboutInfo']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetErrorMessage() {
  return window['go']['app']['App']['GetErrorMessage']();
}

export function GetLogContent() {
  return window['go']['app']['App']['GetLogContent']();
}

export function GetNodes() {
  return window['go']['app']['App']['GetNodes']();
}

export function GetPluginStatus(arg1) {
  return window['go']['app']['App']['GetPluginStatus'](arg1);
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function IsNetworkAdapterReady() {
  return window['go']['app']['App']['IsNetworkAdapterReady']();
}

export function ListPlugins() {
  return window['go']['app']['App']['ListPlugins']();
}

export function OpenLogs() {
  return window['go']['app']['App']['OpenLogs']();
}

export function PluginAction(arg1, arg2) {
  return window['go']['app']['App']['PluginAction'](arg1, arg2);
}
